/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_config.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

AuthZResponse *
requestauthz_1(AuthZRequest *argp, CLIENT *clnt)
{
	static AuthZResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, requestAuthZ,
		(xdrproc_t) xdr_AuthZRequest, (caddr_t) argp,
		(xdrproc_t) xdr_AuthZResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

AuthZResponse *
approveauthz_1(AuthZResponse *argp, CLIENT *clnt)
{
	static AuthZResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, approveAuthZ,
		(xdrproc_t) xdr_AuthZResponse, (caddr_t) argp,
		(xdrproc_t) xdr_AuthZResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

AccessTokenResponse *
generateaccesstoken_1(AccessTokenRequest *argp, CLIENT *clnt)
{
	static AccessTokenResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, generateAccessToken,
		(xdrproc_t) xdr_AccessTokenRequest, (caddr_t) argp,
		(xdrproc_t) xdr_AccessTokenResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

AccessTokenResponse *
refreshaccesstoken_1(AccessTokenRequest *argp, CLIENT *clnt)
{
	static AccessTokenResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, refreshAccessToken,
		(xdrproc_t) xdr_AccessTokenRequest, (caddr_t) argp,
		(xdrproc_t) xdr_AccessTokenResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DelegatedActionResponse *
executedelegatedaction_1(DelegatedAction *argp, CLIENT *clnt)
{
	static DelegatedActionResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, executeDelegatedAction,
		(xdrproc_t) xdr_DelegatedAction, (caddr_t) argp,
		(xdrproc_t) xdr_DelegatedActionResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
