/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_config.h"

bool_t
xdr_AuthZRequest (XDR *xdrs, AuthZRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AuthZResponse (XDR *xdrs, AuthZResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error_code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AccessTokenRequest (XDR *xdrs, AccessTokenRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authz_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->auto_refresh))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AccessTokenResponse (XDR *xdrs, AccessTokenResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->access_token_ttl))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error_code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DelegatedAction (XDR *xdrs, DelegatedAction *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DelegatedActionResponse (XDR *xdrs, DelegatedActionResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error_code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	return TRUE;
}
